#ifndef LIBROCKLEVEL_GLOBAL_H
#define LIBROCKLEVEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBROCKLEVEL_LIBRARY)
#  define LIBROCKLEVELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBROCKLEVELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBROCKLEVEL_GLOBAL_H
